#!/bin/bash

#Home directory for bash projects
srcdir=~/Source/bash-scripts/
echo "Move to script directory..."
cd $srcdir 

#User bin path
installpath=~/bin

scriptname=${1}

echo "Creating required files and folders..."
mkdir $scriptname; cd $scriptname

touch config.json .gitignore

# Create the main script
cat <<'EOF' >>$scriptname
#!/bin/bash
echo $PWD
EOF

# Create the json data
jsondata=$(jq --null-input \
 --arg scriptname $scriptname \
 --arg installpath "$installpath" \
 '{"scriptname": $scriptname, "installpath" : $installpath}')

# Write to the config file
echo $jsondata > config.json
 
# Create the install script
cat <<'EOF' >>install
#!/bin/bash
 
scriptname=$(echo $(jq -r '.scriptname' config.json))
installpath=$(echo $(jq -r '.installpath' config.json))
echo  $installpath
 
cp $scriptname $installpath/$scriptname
echo "Copied ${scriptname} to ${installpath}/${scriptname}"
 
chmod +x $installpath/$scriptname
echo "chmod +x ${installpath}/${scriptname}"            
EOF

# Make the installer executable
chmod +x install

# Create a git repo
echo "Git init"
git init

echo "Installing script..."
cp $scriptname $installpath/$scriptname
chmod +x $installpath/$scriptname

echo "Open new terminal in directory"
cd $srcdir/$scriptname && gnome-terminal

