#!/bin/bash

# script vars
codesource=$(jq -r '.codesource' create-bash-project-config.json)
installdirectory=$(jq -r '.installdirectory' create-bash-project-config.json)
basedatadirectory=$(jq -r '.basedatadirectory' create-bash-project-config.json)

echo $codesource
echo $installdirectory

# exit

function die() {
    printf '%s\n' "$1" >&2
    exit 1
 }
 

function show_help(){
    cat << EOF
    Usage: ${0##*/} [-h --help] [PROJECT NAME]

    Simple script to build command line projects
    
EOF
}


# Check for dependencies
if ! command -v /usr/bin/jq &> /dev/null
then
    echo "`/usr/bin/jq` JSON parsing library not found. \
     Please install jq"
    exit
else
    echo "Library code in place..."
fi


while :; do
   case $1 in
       -h|-\?|--help)
           show_help
           exit
           ;;
       --) # designates end of of options indicator 
           shift
           break
           ;;
       -?*)
           printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
           ;;
       *) # default case break out of loop
           break
    esac

    shift
done


# Has project name has been set?
if [ -z "${1}" ]; then 
    die 'Error: please enter a project name'
else
    scriptname=${1}
    echo $scriptname
fi


# Does script already exist?
if ! command -v ~/bin/$scriptname &> /dev/null
then
    echo "Scriptname is fine..."
else
    die 'Error: ${scriptname} already exists...'
fi


echo "Opening ${codesource}..."
cd $codesource 

echo "Creating required files and folders..."
mkdir $scriptname; cd $scriptname

# Create empty main script
echo "Creating ${scriptname}"
cat <<EOF >$scriptname
#!/bin/bash

echo "Nothing here yet..."

EOF

echo "Creating config files..."
touch $scriptname-config.json .gitignore

datecreated=$(date '+%d/%m/%Y %H:%M:%S')

#create the full data directory path
datadirectory="${basedatadirectory}/${scriptname}"

# Create the json data
jsondata=$(jq --null-input \
 --arg scriptname "$scriptname" \
 --arg installdirectory "$installdirectory" \
 --arg datadirectory "$datadirectory" \
 --arg datecreated "$datecreated" \
  '{"scriptname" : $scriptname, "installdirectory" : $installdirectory, "datadirectory" : $datadirectory, "datecreated" : $datecreated}')

# Write to the config file
echo "Writing config files"
echo $jsondata > $scriptname-config.json


# Create the install script
cat <<EOF >install
#!/bin/bash
 
cp ${scriptname} ${installdirectory}/${scriptname}
echo "Copied ${scriptname} to ${installdirectory}/${scriptname}"
 
chmod +x ${installdirectory}/${scriptname}
echo "chmod +x ${installdirectory}/${scriptname}"            
EOF


# Make the installer executable
chmod +x install


# Create a git repo
echo "Git init"
git init
git add .

git commit -m "Initial commit - ${scriptname} project created on ${datecreated}"


echo "Installing script..."

cp $scriptname $installdirectory/$scriptname
chmod +x $installdirectory/$scriptname


# Installing log files and datastore
# cd $datadirectory
mkdir $datadirectory; cd $datadirectory
touch $scriptname-data.json $scriptname.log

# Is vscode installed 
if command -v /usr/bin/code &> /dev/null
then
    code $codesource/$scriptname
else
    cd $codesource/$scriptname && gnome-terminal
fi